import Foundation
import SwiftUI

public struct MobileFixture: View {
  @Environment(\.colorScheme) private var colorScheme
  public init() {}
  public var body: some View {
    GeometryReader { proxy in
      if colorScheme == .dark && proxy.size.width >= 450 {
        VStack(alignment: .leading, spacing: 18) {
          ZStack(alignment: .topLeading) {
            Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.stroke(Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), style: StrokeStyle(lineWidth: 6, lineCap: .round, lineJoin: .bevel, miterLimit: 4, dash: [12, 8]))).compositingGroup().opacity(1).frame(width: 300, height: 48, alignment: .topLeading).position(x: 150, y: 24)
            Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.stroke(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .square, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 300, height: 4, alignment: .topLeading).position(x: 150, y: 22)
            Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.stroke(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 4, height: 48, alignment: .topLeading).position(x: 150, y: 24)
          }.frame(width: 300, height: 48, alignment: .topLeading).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }.fill(LinearGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), startPoint: UnitPoint(x: 0, y: 0.5), endPoint: UnitPoint(x: 1, y: 0.5)), style: FillStyle(eoFill: false)).overlay(alignment: .topLeading) { Canvas { context, _ in context.translateBy(x: 16, y: 16); let path = Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }; context.clip(to: path, style: FillStyle(eoFill: false), options: []); context.stroke(path, with: .color(Color(red: 0.063, green: 0.125, blue: 0.188, opacity: 1)), style: StrokeStyle(lineWidth: 8, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: [])) }.frame(width: 212, height: 108).offset(x: -16, y: -16) }.compositingGroup().opacity(1).frame(width: 180, height: 76, alignment: .topLeading).scaleEffect(x: -1, y: 1, anchor: .center).rotationEffect(.degrees(18), anchor: .center)
          Ellipse().fill(AngularGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 1, blue: 0, opacity: 1), location: 0.5), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), center: UnitPoint(x: 0.4, y: 0.6), startAngle: .degrees(35), endAngle: .degrees(395))).opacity(1).frame(width: 180, height: 110, alignment: .topLeading)
          Canvas { context, size in let center = CGPoint(x: 0.3 * size.width, y: 0.65 * size.height); let path = Path(CGRect(origin: .zero, size: size)).applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.419).scaledBy(x: 1.429, y: 0.8).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(24)); context.scaleBy(x: 0.7, y: 1.25); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 1, green: 1, blue: 1, opacity: 1), location: 0), .init(color: Color(red: 0.416, green: 0.298, blue: 0.576, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 63)) }.opacity(1).frame(width: 180, height: 90, alignment: .topLeading)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 100, height: 70, alignment: .topLeading).position(x: 290, y: 60)
          }.frame(width: 300, height: 130, alignment: .topLeading).background(Color(red: 0.043, green: 0.29, blue: 0.435, opacity: 1), ignoresSafeAreaEdges: []).clipped().compositingGroup().opacity(1).accessibilityElement(children: .contain)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.914, green: 0.769, blue: 0.416, opacity: 1)).opacity(1).frame(width: 40, height: 30, alignment: .topLeading).position(x: 230, y: 55)
            Rectangle().fill(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1)).opacity(1).frame(width: 50, height: 20, alignment: .topLeading).position(x: 275, y: 60)
          }.frame(width: 300, height: 70, alignment: .bottomLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          HStack(alignment: .top, spacing: 0) {
            Rectangle().fill(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1)).opacity(1).frame(width: 80, height: 40, alignment: .topLeading)
          }.frame(width: 300, height: 60, alignment: .topLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Rectangle().fill(Color(red: 0.416, green: 0.298, blue: 0.576, opacity: 1)).opacity(1).frame(width: 140, height: 24, alignment: .topLeading)
        }.padding(EdgeInsets(top: 80, leading: 20, bottom: 20, trailing: 20)).frame(width: 393, height: 852, alignment: .topLeading).background(Color(red: 0.863, green: 0.918, blue: 0.969, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).accessibilityLabel("Canvas mobile export verification screen").environment(\.locale, Locale(identifier: "en"))
      }
      else if proxy.size.width >= 450 {
        VStack(alignment: .leading, spacing: 18) {
          ZStack(alignment: .topLeading) {
            Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.stroke(Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), style: StrokeStyle(lineWidth: 6, lineCap: .round, lineJoin: .bevel, miterLimit: 4, dash: [12, 8]))).compositingGroup().opacity(1).frame(width: 300, height: 48, alignment: .topLeading).position(x: 150, y: 24)
            Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.stroke(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .square, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 300, height: 4, alignment: .topLeading).position(x: 150, y: 22)
            Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.stroke(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 4, height: 48, alignment: .topLeading).position(x: 150, y: 24)
          }.frame(width: 300, height: 48, alignment: .topLeading).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }.fill(LinearGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), startPoint: UnitPoint(x: 0, y: 0.5), endPoint: UnitPoint(x: 1, y: 0.5)), style: FillStyle(eoFill: false)).overlay(alignment: .topLeading) { Canvas { context, _ in context.translateBy(x: 16, y: 16); let path = Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }; context.clip(to: path, style: FillStyle(eoFill: false), options: []); context.stroke(path, with: .color(Color(red: 0.063, green: 0.125, blue: 0.188, opacity: 1)), style: StrokeStyle(lineWidth: 8, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: [])) }.frame(width: 212, height: 108).offset(x: -16, y: -16) }.compositingGroup().opacity(1).frame(width: 180, height: 76, alignment: .topLeading).scaleEffect(x: -1, y: 1, anchor: .center).rotationEffect(.degrees(18), anchor: .center)
          Ellipse().fill(AngularGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 1, blue: 0, opacity: 1), location: 0.5), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), center: UnitPoint(x: 0.4, y: 0.6), startAngle: .degrees(35), endAngle: .degrees(395))).opacity(1).frame(width: 180, height: 110, alignment: .topLeading)
          Canvas { context, size in let center = CGPoint(x: 0.3 * size.width, y: 0.65 * size.height); let path = Path(CGRect(origin: .zero, size: size)).applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.419).scaledBy(x: 1.429, y: 0.8).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(24)); context.scaleBy(x: 0.7, y: 1.25); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 1, green: 1, blue: 1, opacity: 1), location: 0), .init(color: Color(red: 0.416, green: 0.298, blue: 0.576, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 63)) }.opacity(1).frame(width: 180, height: 90, alignment: .topLeading)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 100, height: 70, alignment: .topLeading).position(x: 290, y: 60)
          }.frame(width: 300, height: 130, alignment: .topLeading).background(Color(red: 0.043, green: 0.29, blue: 0.435, opacity: 1), ignoresSafeAreaEdges: []).clipped().compositingGroup().opacity(1).accessibilityElement(children: .contain)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.914, green: 0.769, blue: 0.416, opacity: 1)).opacity(1).frame(width: 40, height: 30, alignment: .topLeading).position(x: 230, y: 55)
            Rectangle().fill(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1)).opacity(1).frame(width: 50, height: 20, alignment: .topLeading).position(x: 275, y: 60)
          }.frame(width: 300, height: 70, alignment: .bottomLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          HStack(alignment: .top, spacing: 0) {
            Rectangle().fill(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1)).opacity(1).frame(width: 80, height: 40, alignment: .topLeading)
          }.frame(width: 300, height: 60, alignment: .topLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Rectangle().fill(Color(red: 0.914, green: 0.769, blue: 0.416, opacity: 1)).opacity(1).frame(width: 140, height: 24, alignment: .topLeading)
        }.padding(EdgeInsets(top: 80, leading: 20, bottom: 20, trailing: 20)).frame(width: 393, height: 852, alignment: .topLeading).background(Color(red: 0.965, green: 0.949, blue: 0.918, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).accessibilityLabel("Canvas mobile export verification screen").environment(\.locale, Locale(identifier: "en"))
      }
      else if colorScheme == .dark {
        VStack(alignment: .leading, spacing: 18) {
          ZStack(alignment: .topLeading) {
            Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.stroke(Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), style: StrokeStyle(lineWidth: 6, lineCap: .round, lineJoin: .bevel, miterLimit: 4, dash: [12, 8]))).compositingGroup().opacity(1).frame(width: 300, height: 48, alignment: .topLeading).position(x: 150, y: 24)
            Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.stroke(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .square, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 300, height: 4, alignment: .topLeading).position(x: 150, y: 22)
            Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.stroke(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 4, height: 48, alignment: .topLeading).position(x: 150, y: 24)
          }.frame(width: 300, height: 48, alignment: .topLeading).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }.fill(LinearGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), startPoint: UnitPoint(x: 0, y: 0.5), endPoint: UnitPoint(x: 1, y: 0.5)), style: FillStyle(eoFill: false)).overlay(alignment: .topLeading) { Canvas { context, _ in context.translateBy(x: 16, y: 16); let path = Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }; context.clip(to: path, style: FillStyle(eoFill: false), options: []); context.stroke(path, with: .color(Color(red: 0.063, green: 0.125, blue: 0.188, opacity: 1)), style: StrokeStyle(lineWidth: 8, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: [])) }.frame(width: 212, height: 108).offset(x: -16, y: -16) }.compositingGroup().opacity(1).frame(width: 180, height: 76, alignment: .topLeading).scaleEffect(x: -1, y: 1, anchor: .center).rotationEffect(.degrees(18), anchor: .center)
          Ellipse().fill(AngularGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 1, blue: 0, opacity: 1), location: 0.5), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), center: UnitPoint(x: 0.4, y: 0.6), startAngle: .degrees(35), endAngle: .degrees(395))).opacity(1).frame(width: 180, height: 110, alignment: .topLeading)
          Canvas { context, size in let center = CGPoint(x: 0.3 * size.width, y: 0.65 * size.height); let path = Path(CGRect(origin: .zero, size: size)).applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.419).scaledBy(x: 1.429, y: 0.8).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(24)); context.scaleBy(x: 0.7, y: 1.25); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 1, green: 1, blue: 1, opacity: 1), location: 0), .init(color: Color(red: 0.416, green: 0.298, blue: 0.576, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 63)) }.opacity(1).frame(width: 180, height: 90, alignment: .topLeading)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 100, height: 70, alignment: .topLeading).position(x: 290, y: 60)
          }.frame(width: 300, height: 130, alignment: .topLeading).background(Color(red: 0.043, green: 0.29, blue: 0.435, opacity: 1), ignoresSafeAreaEdges: []).clipped().compositingGroup().opacity(1).accessibilityElement(children: .contain)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.914, green: 0.769, blue: 0.416, opacity: 1)).opacity(1).frame(width: 40, height: 30, alignment: .topLeading).position(x: 230, y: 55)
            Rectangle().fill(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1)).opacity(1).frame(width: 50, height: 20, alignment: .topLeading).position(x: 275, y: 60)
          }.frame(width: 300, height: 70, alignment: .bottomLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          HStack(alignment: .top, spacing: 0) {
            Rectangle().fill(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1)).opacity(1).frame(width: 80, height: 40, alignment: .topLeading)
          }.frame(width: 300, height: 60, alignment: .topLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Rectangle().fill(Color(red: 0.416, green: 0.298, blue: 0.576, opacity: 1)).opacity(1).frame(width: 60, height: 24, alignment: .topLeading)
        }.padding(EdgeInsets(top: 80, leading: 20, bottom: 20, trailing: 20)).frame(width: 393, height: 852, alignment: .topLeading).background(Color(red: 0.863, green: 0.918, blue: 0.969, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).accessibilityLabel("Canvas mobile export verification screen").environment(\.locale, Locale(identifier: "en"))
      }
      else {
        VStack(alignment: .leading, spacing: 18) {
          ZStack(alignment: .topLeading) {
            Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 300, y: 48)) }.stroke(Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), style: StrokeStyle(lineWidth: 6, lineCap: .round, lineJoin: .bevel, miterLimit: 4, dash: [12, 8]))).compositingGroup().opacity(1).frame(width: 300, height: 48, alignment: .topLeading).position(x: 150, y: 24)
            Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 0, y: 2)); path.addLine(to: CGPoint(x: 300, y: 2)) }.stroke(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .square, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 300, height: 4, alignment: .topLeading).position(x: 150, y: 22)
            Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.fill(Color(red: 0, green: 0, blue: 0, opacity: 0), style: FillStyle(eoFill: false)).overlay(Path { path in path.move(to: CGPoint(x: 2, y: 0)); path.addLine(to: CGPoint(x: 2, y: 48)) }.stroke(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: []))).compositingGroup().opacity(1).frame(width: 4, height: 48, alignment: .topLeading).position(x: 150, y: 24)
          }.frame(width: 300, height: 48, alignment: .topLeading).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }.fill(LinearGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), startPoint: UnitPoint(x: 0, y: 0.5), endPoint: UnitPoint(x: 1, y: 0.5)), style: FillStyle(eoFill: false)).overlay(alignment: .topLeading) { Canvas { context, _ in context.translateBy(x: 16, y: 16); let path = Path { path in path.move(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 0)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 180, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 76)); path.addLine(to: CGPoint(x: 0, y: 0)); path.addLine(to: CGPoint(x: 0, y: 0)); path.closeSubpath() }; context.clip(to: path, style: FillStyle(eoFill: false), options: []); context.stroke(path, with: .color(Color(red: 0.063, green: 0.125, blue: 0.188, opacity: 1)), style: StrokeStyle(lineWidth: 8, lineCap: .butt, lineJoin: .miter, miterLimit: 4, dash: [])) }.frame(width: 212, height: 108).offset(x: -16, y: -16) }.compositingGroup().opacity(1).frame(width: 180, height: 76, alignment: .topLeading).scaleEffect(x: -1, y: 1, anchor: .center).rotationEffect(.degrees(18), anchor: .center)
          Ellipse().fill(AngularGradient(gradient: Gradient(stops: [.init(color: Color(red: 1, green: 0, blue: 0, opacity: 1), location: 0), .init(color: Color(red: 0, green: 1, blue: 0, opacity: 1), location: 0.5), .init(color: Color(red: 0, green: 0, blue: 1, opacity: 1), location: 1)]), center: UnitPoint(x: 0.4, y: 0.6), startAngle: .degrees(35), endAngle: .degrees(395))).opacity(1).frame(width: 180, height: 110, alignment: .topLeading)
          Canvas { context, size in let center = CGPoint(x: 0.3 * size.width, y: 0.65 * size.height); let path = Path(CGRect(origin: .zero, size: size)).applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.419).scaledBy(x: 1.429, y: 0.8).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(24)); context.scaleBy(x: 0.7, y: 1.25); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 1, green: 1, blue: 1, opacity: 1), location: 0), .init(color: Color(red: 0.416, green: 0.298, blue: 0.576, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 63)) }.opacity(1).frame(width: 180, height: 90, alignment: .topLeading)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 100, height: 70, alignment: .topLeading).position(x: 290, y: 60)
          }.frame(width: 300, height: 130, alignment: .topLeading).background(Color(red: 0.043, green: 0.29, blue: 0.435, opacity: 1), ignoresSafeAreaEdges: []).clipped().compositingGroup().opacity(1).accessibilityElement(children: .contain)
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.914, green: 0.769, blue: 0.416, opacity: 1)).opacity(1).frame(width: 40, height: 30, alignment: .topLeading).position(x: 230, y: 55)
            Rectangle().fill(Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1)).opacity(1).frame(width: 50, height: 20, alignment: .topLeading).position(x: 275, y: 60)
          }.frame(width: 300, height: 70, alignment: .bottomLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          HStack(alignment: .top, spacing: 0) {
            Rectangle().fill(Color(red: 0.906, green: 0.435, blue: 0.318, opacity: 1)).opacity(1).frame(width: 80, height: 40, alignment: .topLeading)
          }.frame(width: 300, height: 60, alignment: .topLeading).background(Color(red: 0.149, green: 0.275, blue: 0.325, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1).accessibilityElement(children: .contain)
          Rectangle().fill(Color(red: 0.914, green: 0.769, blue: 0.416, opacity: 1)).opacity(1).frame(width: 60, height: 24, alignment: .topLeading)
        }.padding(EdgeInsets(top: 80, leading: 20, bottom: 20, trailing: 20)).frame(width: 393, height: 852, alignment: .topLeading).background(Color(red: 0.965, green: 0.949, blue: 0.918, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).accessibilityLabel("Canvas mobile export verification screen").environment(\.locale, Locale(identifier: "en"))
      }
    }
  }
}
