import Foundation
import SwiftUI

public struct FlowPaintRoundedScalarOverflow: View {
  @Environment(\.colorScheme) private var colorScheme
  public init() {}
  public var body: some View {
    GeometryReader { proxy in
      if colorScheme == .dark && proxy.size.width >= 480 {
        ZStack(alignment: .topLeading) {
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 392, height: 46, alignment: .topLeading).position(x: 180, y: 65)
          }.frame(width: 360, height: 130, alignment: .topLeading).background(alignment: .topLeading) { Canvas { context, size in let center = CGPoint(x: 0.27 * size.width, y: 0.68 * size.height); let path = Path { path in path.move(to: CGPoint(x: 12, y: 0)); path.addLine(to: CGPoint(x: 332, y: 0)); path.addCurve(to: CGPoint(x: 360, y: 28), control1: CGPoint(x: 347.464, y: 0), control2: CGPoint(x: 360, y: 12.536)); path.addLine(to: CGPoint(x: 360, y: 86)); path.addCurve(to: CGPoint(x: 316, y: 130), control1: CGPoint(x: 360, y: 110.301), control2: CGPoint(x: 340.301, y: 130)); path.addLine(to: CGPoint(x: 20, y: 130)); path.addCurve(to: CGPoint(x: 0, y: 110), control1: CGPoint(x: 8.954, y: 130), control2: CGPoint(x: 0, y: 121.046)); path.addLine(to: CGPoint(x: 0, y: 12)); path.addCurve(to: CGPoint(x: 12, y: 0), control1: CGPoint(x: 0, y: 5.373), control2: CGPoint(x: 5.373, y: 0)); path.closeSubpath() }.applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.541).scaledBy(x: 2.273, y: 1.389).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(31)); context.scaleBy(x: 0.44, y: 0.72); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1), location: 0), .init(color: Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), location: 0.45), .init(color: Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 79.2)) }.opacity(1) }.compositingGroup().opacity(1).position(x: 210, y: 95).accessibilityElement(children: .contain)
        }.frame(width: 420, height: 360, alignment: .topLeading).background(Color(red: 0.965, green: 0.949, blue: 0.918, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).environment(\.locale, Locale(identifier: "en"))
      }
      else if proxy.size.width >= 480 {
        ZStack(alignment: .topLeading) {
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 392, height: 46, alignment: .topLeading).position(x: 180, y: 65)
          }.frame(width: 360, height: 130, alignment: .topLeading).background(alignment: .topLeading) { Canvas { context, size in let center = CGPoint(x: 0.27 * size.width, y: 0.68 * size.height); let path = Path { path in path.move(to: CGPoint(x: 12, y: 0)); path.addLine(to: CGPoint(x: 332, y: 0)); path.addCurve(to: CGPoint(x: 360, y: 28), control1: CGPoint(x: 347.464, y: 0), control2: CGPoint(x: 360, y: 12.536)); path.addLine(to: CGPoint(x: 360, y: 86)); path.addCurve(to: CGPoint(x: 316, y: 130), control1: CGPoint(x: 360, y: 110.301), control2: CGPoint(x: 340.301, y: 130)); path.addLine(to: CGPoint(x: 20, y: 130)); path.addCurve(to: CGPoint(x: 0, y: 110), control1: CGPoint(x: 8.954, y: 130), control2: CGPoint(x: 0, y: 121.046)); path.addLine(to: CGPoint(x: 0, y: 12)); path.addCurve(to: CGPoint(x: 12, y: 0), control1: CGPoint(x: 0, y: 5.373), control2: CGPoint(x: 5.373, y: 0)); path.closeSubpath() }.applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.541).scaledBy(x: 2.273, y: 1.389).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(31)); context.scaleBy(x: 0.44, y: 0.72); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1), location: 0), .init(color: Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), location: 0.45), .init(color: Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 79.2)) }.opacity(1) }.compositingGroup().opacity(1).position(x: 210, y: 95).accessibilityElement(children: .contain)
        }.frame(width: 420, height: 360, alignment: .topLeading).background(Color(red: 0.965, green: 0.949, blue: 0.918, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).environment(\.locale, Locale(identifier: "en"))
      }
      else if colorScheme == .dark {
        ZStack(alignment: .topLeading) {
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 392, height: 46, alignment: .topLeading).position(x: 180, y: 65)
          }.frame(width: 360, height: 130, alignment: .topLeading).background(alignment: .topLeading) { Canvas { context, size in let center = CGPoint(x: 0.27 * size.width, y: 0.68 * size.height); let path = Path { path in path.move(to: CGPoint(x: 12, y: 0)); path.addLine(to: CGPoint(x: 332, y: 0)); path.addCurve(to: CGPoint(x: 360, y: 28), control1: CGPoint(x: 347.464, y: 0), control2: CGPoint(x: 360, y: 12.536)); path.addLine(to: CGPoint(x: 360, y: 86)); path.addCurve(to: CGPoint(x: 316, y: 130), control1: CGPoint(x: 360, y: 110.301), control2: CGPoint(x: 340.301, y: 130)); path.addLine(to: CGPoint(x: 20, y: 130)); path.addCurve(to: CGPoint(x: 0, y: 110), control1: CGPoint(x: 8.954, y: 130), control2: CGPoint(x: 0, y: 121.046)); path.addLine(to: CGPoint(x: 0, y: 12)); path.addCurve(to: CGPoint(x: 12, y: 0), control1: CGPoint(x: 0, y: 5.373), control2: CGPoint(x: 5.373, y: 0)); path.closeSubpath() }.applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.541).scaledBy(x: 2.273, y: 1.389).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(31)); context.scaleBy(x: 0.44, y: 0.72); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1), location: 0), .init(color: Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), location: 0.45), .init(color: Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 79.2)) }.opacity(1) }.compositingGroup().opacity(1).position(x: 210, y: 95).accessibilityElement(children: .contain)
        }.frame(width: 420, height: 360, alignment: .topLeading).background(Color(red: 0.965, green: 0.949, blue: 0.918, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).environment(\.locale, Locale(identifier: "en"))
      }
      else {
        ZStack(alignment: .topLeading) {
          ZStack(alignment: .topLeading) {
            Rectangle().fill(Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1)).opacity(1).frame(width: 392, height: 46, alignment: .topLeading).position(x: 180, y: 65)
          }.frame(width: 360, height: 130, alignment: .topLeading).background(alignment: .topLeading) { Canvas { context, size in let center = CGPoint(x: 0.27 * size.width, y: 0.68 * size.height); let path = Path { path in path.move(to: CGPoint(x: 12, y: 0)); path.addLine(to: CGPoint(x: 332, y: 0)); path.addCurve(to: CGPoint(x: 360, y: 28), control1: CGPoint(x: 347.464, y: 0), control2: CGPoint(x: 360, y: 12.536)); path.addLine(to: CGPoint(x: 360, y: 86)); path.addCurve(to: CGPoint(x: 316, y: 130), control1: CGPoint(x: 360, y: 110.301), control2: CGPoint(x: 340.301, y: 130)); path.addLine(to: CGPoint(x: 20, y: 130)); path.addCurve(to: CGPoint(x: 0, y: 110), control1: CGPoint(x: 8.954, y: 130), control2: CGPoint(x: 0, y: 121.046)); path.addLine(to: CGPoint(x: 0, y: 12)); path.addCurve(to: CGPoint(x: 12, y: 0), control1: CGPoint(x: 0, y: 5.373), control2: CGPoint(x: 5.373, y: 0)); path.closeSubpath() }.applying(CGAffineTransform(translationX: center.x, y: center.y).rotated(by: -0.541).scaledBy(x: 2.273, y: 1.389).translatedBy(x: -center.x, y: -center.y)); context.translateBy(x: center.x, y: center.y); context.rotate(by: .degrees(31)); context.scaleBy(x: 0.44, y: 0.72); context.translateBy(x: -center.x, y: -center.y); context.fill(path, with: .radialGradient(Gradient(stops: [.init(color: Color(red: 0.957, green: 0.635, blue: 0.38, opacity: 1), location: 0), .init(color: Color(red: 0.165, green: 0.616, blue: 0.561, opacity: 1), location: 0.45), .init(color: Color(red: 0.071, green: 0.204, blue: 0.337, opacity: 1), location: 1)]), center: center, startRadius: 0, endRadius: 79.2)) }.opacity(1) }.compositingGroup().opacity(1).position(x: 210, y: 95).accessibilityElement(children: .contain)
        }.frame(width: 420, height: 360, alignment: .topLeading).background(Color(red: 0.965, green: 0.949, blue: 0.918, opacity: 1), ignoresSafeAreaEdges: []).compositingGroup().opacity(1)
        .accessibilityElement(children: .contain).environment(\.locale, Locale(identifier: "en"))
      }
    }
  }
}
